### PR TITLE
Added Share and New Canvas Controls

### PR DESCRIPTION
**Pull request by Tornquist**
# :green_heart: Summary

Added Navigation Items to demo app
- Share button that sends the UIImage to available apps
- Compose button to get a new canvas
- Updated control panel drawing so navbar and control panel match.

### CODE REVIEW

**Comment by e7711bbear** [comment]
Conflicts, please resolve.

**Comment by Tornquist** [comment]
Resolved.

**Comment by Tornquist** [comment]
Wait to merge this!

**Comment by Tornquist** [comment]
Conflicts resolved.  This should be good to go.

**Comment by e7711bbear** [comment]
Thanks for the PR. :+1:

**Pull request merged**
